
#include "config.h" // config.h is generated by cmake and may contain usefull information
#include "stdio.h"
#include "stdlib.h"
#include "pthread.h"

static int get_random (int max)
{
   double val;

   val = (double) max * rand ();
   val = val / (RAND_MAX + 1.0);

   return ((int) val);
}

void * arbitrary_work(void * p_data)
{
    while(1)
    {
        int trigger = get_random(1000000);
        if(0 == trigger)
        {
            printf("Fuck yeah\n");
        }
    }

    return NULL;
}


int main(int argc, char * argv[])
{
    printf("hey guys\n");
    pthread_t my_thread1;
    pthread_t my_thread2;
    
    pthread_create(&my_thread1, 0, arbitrary_work, 0);
    pthread_create(&my_thread2, 0, arbitrary_work, 0);

    void * thread_ret = NULL;
    pthread_join(my_thread1, &thread_ret);
    pthread_join(my_thread2, &thread_ret);
    
    return 0;
}

