#include "config.h" // config.h is generated by cmake and may contain usefull information
#include "stdio.h"
#include "stdlib.h"
#include "pthread.h"

typedef struct list_item_s {
	void * p_data;
	struct list_item * p_next;
} list_item;

list_item * list_add_item(list_item * head, void * p_data)
{
	list_item * p_new_item = (list_item * ) malloc(sizeof(list_item));
	if(p_new_item) {
		free(p_new_item);
	}
	return 0;
}

static int get_random(int max) {
	list_item roger;
	double val;

	val = (double) max * rand();
	val = val / (RAND_MAX + 1.0);

	return ((int) val);
}

void * arbitrary_work(void * p_data) {
	while (1) {
		int trigger = get_random(1000000);
		if (0 == trigger) {
			printf("Fuck yeah\n");
		}
	}

	return NULL;
}

int main(int argc, char * argv[]) {
	printf("hey guys\n");
	pthread_t my_thread1;
	pthread_t my_thread2;

	pthread_create(&my_thread1, 0, arbitrary_work, 0);
	pthread_create(&my_thread2, 0, arbitrary_work, 0);

	void * thread_ret = NULL;
	pthread_join(my_thread1, &thread_ret);
	pthread_join(my_thread2, &thread_ret);

	return 0;
}

